### ISSUE TITLE
Einstein Activity Capture support?

### ISSUE THREAD

**Issue by jclark-dot-org** [SalesforceLabs/ActivityTimelineLWC#1]
Does this component display emails captured by Einstein Activity Capture?  The standard activity timeline does so, although as far as I know, they are not captured as Tasks or EmailMessages within SF, which has led to issues with a proposed custom timeline solution.  Can this component display such emails?

**Comment by rbklaassen** [comment]
Hi @jclark-dot-org, not sure if this is still relevant, but the app has the ability to create an apex dataprovider for use cases other than the standard child relationships. If activity capture emails are not part of the child relationships, a developer could create an apex dataprovider to retrieve the data from the source of these emails.
