### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by barouchk** [SalesforceLabs/ActivityTimelineLWC#14]
When expending one item and there is a text inside, there is no option to reach the text inside for blind customers by clicking the tab button.

what happened was that it skipped the text inside and moved to the next expandable tab and not the content inside.

found a quick solution for that, to put tabindex="0" on the texts inside the inside div

for example:

if there are 2 links and a description inside to expendable tab the system will move to the first 2 links but will skip the description.

<img width="1062" alt="Screenshot 2023-12-18 at 9 15 29" src="https://github.com/SalesforceLabs/ActivityTimelineLWC/assets/13333244/157db077-4898-4e6a-afac-b26660f971e6">

**Comment by barouchk** [comment]
option to fix:
in lwc component: timelineItemDetail.html
need to add tabindex="0" in line 7:
`                    <div class="slds-form-element__static" tabindex="0">`

**Comment by rbklaassen** [comment]
Thanks @barouchk, this will be added to the new version!
