### ISSUE TITLE
Refresh timeline programmatically

### ISSUE THREAD

**Issue by ArielS1** [SalesforceLabs/ActivityTimelineLWC#15]
Hi,

I have a flexipage that shows a timeline.
After i insert a record using a flow from a quick action it suppose to be shown on the timeline, but it will be shown only after manually clicking the refresh button on the timeline.

It would be awesome if there would be a message channel that would refresh the data so i could send the command programatically from an LWC that is outside the timeline in the same flexipage.

**Comment by rbklaassen** [comment]
Added this request to the feature requests @ArielS1 : https://salesforce.quip.com/2bkIAlz5vV36
