### ISSUE TITLE
All  subTitle fields are not being displayed

### ISSUE THREAD

**Issue by djs959** [SalesforceLabs/ActivityTimelineLWC#21]
If more than one sub title field is provided in the config, only the first is displayed if there is only one title field, if there is more than one title field than that number of sub title fields are displayed. 

The issue appears to be this line,

https://github.com/SalesforceLabs/ActivityTimelineLWC/blob/75a24b4e9d1b93a129d2f56391e816ede2acb5b9/force-app/main/default/lwc/activityTimeline/activityTimeline.js#L379

It should be 
for(let i=0;i<subTitleFields.length;i++)

**Comment by rbklaassen** [comment]
Thanks @djs959, it was fixed in the new release!
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t4T000001Dvuz
