### ISSUE TITLE
Timeline User Permission Sets are missing field permissions

### ISSUE THREAD

**Issue by jmdohn** [SalesforceLabs/ActivityTimelineLWC#3]
The timeline permission set is missing two permissions, resulting in a "no data" error for users.

1. Display Relative Dates is missing on Timeline Configurations
![Screen Shot 2021-06-14 at 3 32 43 PM](https://user-images.githubusercontent.com/12724534/121955922-2057ac00-cd26-11eb-9c76-45578b2f8e2c.png)

2. Overdue Field is missing on Timeline Child Objects
![Screen Shot 2021-06-14 at 3 32 27 PM](https://user-images.githubusercontent.com/12724534/121955885-12099000-cd26-11eb-8db5-06f5c4650397.png)

Reproduction:
1. Create a new hands on org.
2. Navigate to "Playground Starter" app.
3. Click on "Install a package" and enter "04t4T000000xA2rQAE".
4. Install for Admins Only.
5. Create a timeline configuration for the Opportunity object.
6. Add a child object of tasks with the Title Field as "Subject", the date field as "Activity Date" and select "Status" & "Priority" as additional fields.
7. Add the configuration to the opportunity page.
8. Create a new user with the "Custom: Sales User" profile.
9. Add the Timeline User permission set to the user.
10. Login as the user.
11. See the no data returned error.

Expected Result:
![Screen Shot 2021-06-14 at 3 42 50 PM](https://user-images.githubusercontent.com/12724534/121956849-387bfb00-cd27-11eb-8562-e4d0d5adcfab.png)

Actual Result:
![Screen Shot 2021-06-14 at 3 48 13 PM](https://user-images.githubusercontent.com/12724534/121957400-f43d2a80-cd27-11eb-8f12-01af3ad1ac8e.png)

**Comment by rbklaassen** [comment]
This has been fixed in the mean time!
