### ISSUE TITLE
ContentNote link does not work

### ISSUE THREAD

**Issue by silverlakezombie** [SalesforceLabs/ActivityTimelineLWC#6]
When you click on a content note in the timeline, the link redirects to "/lightning/r/AttachedContentNote/[ContentNoteId]/view" where it should be going to "/lightning/o/ContentNote/home?recordId=[ContentNoteId]" so the note is viewable with rich text editor. 

Also, when you expand a ContentNote in Timeline, none of the selected fields resolve and preview.

**Comment by rbklaassen** [comment]
Thanks for submitting this issue!
The link to the correct page is fixed in release 3.19 @silverlakezombie

**Comment by rbklaassen** [comment]
Unfortunately, AttachedContentNote cannot be queried: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_attachedcontentnote.htm
So we would need to create a workaround solution only for this object to be able to resolve fields. I'm afraid we will not pick this up on short notice...
